stages:
- test
- release

sonarcloud-frontend-sast:
  stage: test
  rules:
  - if: $SAST_DISABLED == 'true' || $SAST_DISABLED == '1'
    when: never
  - if: $CI_COMMIT_BRANCH && $CI_COMMIT_MESSAGE =~ /do tests/
    changes:
    - frontend/**/*
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
    - .sonar/cache
  script:
  - >
    sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=${SONAR_PROJECT_KEY_FRONTEND} -Dsonar.host.url=${SONAR_PROJECT_URL} -Dsonar.login=${SONAR_LOGIN} -Dsonar.sources=./frontend
  allow_failure: true

upload-frontend-release:
  stage: release
  image:
    name: docker:26.0.2-alpine3.19
  services:
  - name: docker:26.0.2
    alias: docker
  script:
  - cd ${CI_PROJECT_DIR}/frontend
  - echo ${AUTHORIZED_KEY} | base64 -d | docker login -u json_key --password-stdin cr.yandex
  - >
    docker build -t cr.yandex/${YANDEX_REGISTRY}/frontend:$VERSION -t cr.yandex/${YANDEX_REGISTRY}/frontend:latest .
  - docker push cr.yandex/${YANDEX_REGISTRY}/frontend:$VERSION
  - docker push cr.yandex/${YANDEX_REGISTRY}/frontend:latest
  rules:
  - if: $CI_COMMIT_BRANCH
    when: manual
