# Default values for helm-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

containerRegistry: cr.yandex/crp9fshv48uet31urbjn

imagePullPolicy: IfNotPresent
revisionHistoryLimit: 5
environment: dev

imagePullSecrets: []
nameOverride: "momo-store"
fullnameOverride: "momo-store-chart"

backend:
  image:
    repository: backend
    tag: "latest"
  replicas: 1
  minReadySeconds: 10
  rollingUpdate:
    maxUnavailable: 1
  servicePort: 8081
  resourcePolicy:
    minAllowedCPU: 0M
    maxAllowedCPU: 800M
    minAllowedMemory: 200Mi
    maxAllowedMemory: 1000Mi
