name: momo-store

x-default: &default
  healthcheck:
    interval: 30s
    timeout: 5s
    retries: 5
    start_period: 10s
  build:
    dockerfile: ./Dockerfile
  restart: unless-stopped

services:
  backend:
    image: backend:latest
    build:
      context: ./backend
    expose:
      - "8081"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8081/health"]
    <<: *default

  frontend:
    image: frontend:latest
    build:
      context: ./frontend
    ports:
      - 80:80
    healthcheck:
      test: ["CMD", "nc", "-vz", "-w1", "frontend", "80"]
    configs:
      - source: nginx-default.conf
        target: /etc/nginx/conf.d/default.conf
    <<: *default

configs:
  nginx-default.conf:
    file: ./frontend/nginx-default.conf
    name: nginx-default.conf