---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-conf
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |-
    server {
        listen {{ .Values.frontend.servicePort }};
        listen [::]:{{ .Values.frontend.servicePort }};

        server_name {{ .Values.frontend.host }};

        rewrite /momo-store/(.*) /$1 break;

        location / {
            root /opt/www;
            try_files $uri $uri/ /index.html =404;
            access_log off;
            log_not_found off;
        }

        location = /favicon.ico {
            root /opt/www;
            access_log off;
            log_not_found off;
        }

        location ~* ^/(css|js|img)/(.+\.(css|js|gif|jpe?g|png)) {
            root /opt/www;
            expires 30d;
        }

        location ~* /(products|categories|catalog|metrics)/(.*) {
            proxy_pass http://backend:8081/$1/$2;
            proxy_http_version 1.1;
        }

        location /auth/whoami {
            proxy_pass http://backend:8081;
            proxy_http_version 1.1;
        }

        include  /etc/nginx/mime.types;
    }
